/**
 * Compatibility constants for the future rental booking FSM.
 *
 * This phase does NOT implement the full state machine or payment holds.
 * New marketplace requests may snapshot PENDING_SUPPLIER_CONFIRMATION.
 * Blocking uses these constants when `order.bookingStatus` is set;
 * otherwise falls back to legacy `confirmed` / `offline`.
 *
 * Future mapping (holds phase):
 *   CONFIRMED_AWAITING_PAYMENT          — hard-block (temporary hold)
 *   ALTERNATIVE_ACCEPTED_AWAITING_PAYMENT — hard-block
 *   PAYMENT_PROCESSING                  — hard-block
 *   BOOKING_CONFIRMED                   — hard-block
 *   COMPLETED                           — hard-block for those dates
 *   PENDING_SUPPLIER_CONFIRMATION       — does not hard-block
 *   ALTERNATIVE_PROPOSED                — does not hard-block
 *   SUPPLIER_DECLINED / NO_AVAILABILITY — do not block
 *   PAYMENT_EXPIRED / cancelled         — do not block
 */

export const BOOKING_STATUS = {
  PENDING_SUPPLIER_CONFIRMATION: "PENDING_SUPPLIER_CONFIRMATION",
  ALTERNATIVE_PROPOSED: "ALTERNATIVE_PROPOSED",
  ALTERNATIVE_ACCEPTED_AWAITING_PAYMENT:
    "ALTERNATIVE_ACCEPTED_AWAITING_PAYMENT",
  SUPPLIER_DECLINED: "SUPPLIER_DECLINED",
  NO_AVAILABILITY: "NO_AVAILABILITY",
  CONFIRMED_AWAITING_PAYMENT: "CONFIRMED_AWAITING_PAYMENT",
  PAYMENT_PROCESSING: "PAYMENT_PROCESSING",
  PAYMENT_EXPIRED: "PAYMENT_EXPIRED",
  BOOKING_CONFIRMED: "BOOKING_CONFIRMED",
  COMPLETED: "COMPLETED",
  CUSTOMER_CANCELLED: "CUSTOMER_CANCELLED",
  SUPPLIER_CANCELLED: "SUPPLIER_CANCELLED",
  ADMIN_CANCELLED: "ADMIN_CANCELLED",
};

export const HARD_BLOCKING_BOOKING_STATUSES = [
  BOOKING_STATUS.CONFIRMED_AWAITING_PAYMENT,
  BOOKING_STATUS.ALTERNATIVE_ACCEPTED_AWAITING_PAYMENT,
  BOOKING_STATUS.PAYMENT_PROCESSING,
  BOOKING_STATUS.BOOKING_CONFIRMED,
  BOOKING_STATUS.COMPLETED,
];

export const NON_BLOCKING_BOOKING_STATUSES = [
  BOOKING_STATUS.PENDING_SUPPLIER_CONFIRMATION,
  BOOKING_STATUS.ALTERNATIVE_PROPOSED,
  BOOKING_STATUS.SUPPLIER_DECLINED,
  BOOKING_STATUS.NO_AVAILABILITY,
  BOOKING_STATUS.PAYMENT_EXPIRED,
  BOOKING_STATUS.CUSTOMER_CANCELLED,
  BOOKING_STATUS.SUPPLIER_CANCELLED,
  BOOKING_STATUS.ADMIN_CANCELLED,
];

const HARD_SET = new Set(HARD_BLOCKING_BOOKING_STATUSES);
const NON_SET = new Set(NON_BLOCKING_BOOKING_STATUSES);

export function isHardBlockingBookingStatus(status) {
  return HARD_SET.has(String(status || "").trim());
}

export function isNonBlockingBookingStatus(status) {
  return NON_SET.has(String(status || "").trim());
}
