/**
 * Transfer order state machine (separate from rental ORDER_STATUS).
 */

export const TRANSFER_STATUS = {
  DRAFT: "DRAFT",
  QUOTED: "QUOTED",
  MANUAL_QUOTE_REQUIRED: "MANUAL_QUOTE_REQUIRED",
  AWAITING_ADMIN_QUOTE: "AWAITING_ADMIN_QUOTE",
  OPEN_FOR_CLAIM: "OPEN_FOR_CLAIM",
  CLAIMED: "CLAIMED",
  AWAITING_CUSTOMER_PAYMENT: "AWAITING_CUSTOMER_PAYMENT",
  CONFIRMED: "CONFIRMED",
  DRIVER_ASSIGNED: "DRIVER_ASSIGNED",
  DRIVER_EN_ROUTE: "DRIVER_EN_ROUTE",
  PASSENGER_PICKED_UP: "PASSENGER_PICKED_UP",
  COMPLETED: "COMPLETED",
  EXPIRED_UNCLAIMED: "EXPIRED_UNCLAIMED",
  CUSTOMER_CANCELLED: "CUSTOMER_CANCELLED",
  SUPPLIER_CANCELLED: "SUPPLIER_CANCELLED",
  ADMIN_CANCELLED: "ADMIN_CANCELLED",
  REOPENED_FOR_CLAIM: "REOPENED_FOR_CLAIM",
  REFUND_PENDING: "REFUND_PENDING",
  REFUNDED: "REFUNDED",
  DISPUTED: "DISPUTED",
  /** @deprecated legacy lowercase — mapped in normalizeTransferStatus */
  OPEN: "open",
  NEW: "new",
  SEEN: "seen",
  DONE: "done",
  CANCELLED: "cancelled",
  CLAIMED_LEGACY: "claimed",
};

/** Statuses that accept supplier claims. */
export const TRANSFER_CLAIMABLE_STATUSES = [
  TRANSFER_STATUS.OPEN_FOR_CLAIM,
  TRANSFER_STATUS.REOPENED_FOR_CLAIM,
  // legacy
  "open",
  "new",
  "seen",
];

export const TRANSFER_OPEN_STATUSES = TRANSFER_CLAIMABLE_STATUSES;

export const TRANSFER_CANCELLED_STATUSES = [
  TRANSFER_STATUS.CUSTOMER_CANCELLED,
  TRANSFER_STATUS.SUPPLIER_CANCELLED,
  TRANSFER_STATUS.ADMIN_CANCELLED,
  "cancelled",
];

const LEGACY_MAP = {
  open: TRANSFER_STATUS.OPEN_FOR_CLAIM,
  new: TRANSFER_STATUS.OPEN_FOR_CLAIM,
  seen: TRANSFER_STATUS.OPEN_FOR_CLAIM,
  claimed: TRANSFER_STATUS.CLAIMED,
  done: TRANSFER_STATUS.COMPLETED,
  cancelled: TRANSFER_STATUS.ADMIN_CANCELLED,
};

export function normalizeTransferStatus(status) {
  const raw = String(status || "").trim();
  if (!raw) return TRANSFER_STATUS.OPEN_FOR_CLAIM;
  if (LEGACY_MAP[raw]) return LEGACY_MAP[raw];
  if (Object.values(TRANSFER_STATUS).includes(raw)) return raw;
  return raw;
}

export function isTransferOpenStatus(status) {
  return TRANSFER_CLAIMABLE_STATUSES.includes(String(status || ""));
}

export function isTransferClaimable(status) {
  return isTransferOpenStatus(status);
}

/**
 * Allowed transitions: from → Set of to.
 * Actors are documented in comments; enforced in transitionTransferStatus.
 */
export const TRANSFER_TRANSITIONS = {
  [TRANSFER_STATUS.DRAFT]: [
    TRANSFER_STATUS.QUOTED,
    TRANSFER_STATUS.MANUAL_QUOTE_REQUIRED,
    TRANSFER_STATUS.AWAITING_ADMIN_QUOTE,
    TRANSFER_STATUS.OPEN_FOR_CLAIM,
    TRANSFER_STATUS.CUSTOMER_CANCELLED,
    TRANSFER_STATUS.ADMIN_CANCELLED,
  ],
  [TRANSFER_STATUS.QUOTED]: [
    TRANSFER_STATUS.OPEN_FOR_CLAIM,
    TRANSFER_STATUS.MANUAL_QUOTE_REQUIRED,
    TRANSFER_STATUS.CUSTOMER_CANCELLED,
    TRANSFER_STATUS.ADMIN_CANCELLED,
  ],
  [TRANSFER_STATUS.MANUAL_QUOTE_REQUIRED]: [
    TRANSFER_STATUS.AWAITING_ADMIN_QUOTE,
    TRANSFER_STATUS.QUOTED,
    TRANSFER_STATUS.OPEN_FOR_CLAIM,
    TRANSFER_STATUS.ADMIN_CANCELLED,
    TRANSFER_STATUS.CUSTOMER_CANCELLED,
  ],
  [TRANSFER_STATUS.AWAITING_ADMIN_QUOTE]: [
    TRANSFER_STATUS.QUOTED,
    TRANSFER_STATUS.OPEN_FOR_CLAIM,
    TRANSFER_STATUS.ADMIN_CANCELLED,
  ],
  [TRANSFER_STATUS.OPEN_FOR_CLAIM]: [
    TRANSFER_STATUS.CLAIMED,
    TRANSFER_STATUS.EXPIRED_UNCLAIMED,
    TRANSFER_STATUS.CUSTOMER_CANCELLED,
    TRANSFER_STATUS.ADMIN_CANCELLED,
  ],
  [TRANSFER_STATUS.REOPENED_FOR_CLAIM]: [
    TRANSFER_STATUS.CLAIMED,
    TRANSFER_STATUS.EXPIRED_UNCLAIMED,
    TRANSFER_STATUS.ADMIN_CANCELLED,
    TRANSFER_STATUS.CUSTOMER_CANCELLED,
  ],
  [TRANSFER_STATUS.CLAIMED]: [
    TRANSFER_STATUS.AWAITING_CUSTOMER_PAYMENT,
    TRANSFER_STATUS.CONFIRMED,
    TRANSFER_STATUS.SUPPLIER_CANCELLED,
    TRANSFER_STATUS.CUSTOMER_CANCELLED,
    TRANSFER_STATUS.ADMIN_CANCELLED,
  ],
  [TRANSFER_STATUS.AWAITING_CUSTOMER_PAYMENT]: [
    TRANSFER_STATUS.CONFIRMED,
    TRANSFER_STATUS.CUSTOMER_CANCELLED,
    TRANSFER_STATUS.ADMIN_CANCELLED,
    TRANSFER_STATUS.REFUND_PENDING,
  ],
  [TRANSFER_STATUS.CONFIRMED]: [
    TRANSFER_STATUS.DRIVER_ASSIGNED,
    TRANSFER_STATUS.COMPLETED,
    TRANSFER_STATUS.SUPPLIER_CANCELLED,
    TRANSFER_STATUS.CUSTOMER_CANCELLED,
    TRANSFER_STATUS.ADMIN_CANCELLED,
    TRANSFER_STATUS.DISPUTED,
  ],
  [TRANSFER_STATUS.DRIVER_ASSIGNED]: [
    TRANSFER_STATUS.DRIVER_EN_ROUTE,
    TRANSFER_STATUS.PASSENGER_PICKED_UP,
    TRANSFER_STATUS.COMPLETED,
    TRANSFER_STATUS.SUPPLIER_CANCELLED,
    TRANSFER_STATUS.ADMIN_CANCELLED,
  ],
  [TRANSFER_STATUS.DRIVER_EN_ROUTE]: [
    TRANSFER_STATUS.PASSENGER_PICKED_UP,
    TRANSFER_STATUS.COMPLETED,
    TRANSFER_STATUS.SUPPLIER_CANCELLED,
    TRANSFER_STATUS.ADMIN_CANCELLED,
  ],
  [TRANSFER_STATUS.PASSENGER_PICKED_UP]: [
    TRANSFER_STATUS.COMPLETED,
    TRANSFER_STATUS.DISPUTED,
    TRANSFER_STATUS.ADMIN_CANCELLED,
  ],
  [TRANSFER_STATUS.SUPPLIER_CANCELLED]: [
    TRANSFER_STATUS.REOPENED_FOR_CLAIM,
    TRANSFER_STATUS.ADMIN_CANCELLED,
    TRANSFER_STATUS.EXPIRED_UNCLAIMED,
  ],
  [TRANSFER_STATUS.EXPIRED_UNCLAIMED]: [
    TRANSFER_STATUS.REOPENED_FOR_CLAIM,
    TRANSFER_STATUS.OPEN_FOR_CLAIM,
    TRANSFER_STATUS.ADMIN_CANCELLED,
  ],
  [TRANSFER_STATUS.COMPLETED]: [
    TRANSFER_STATUS.DISPUTED,
    TRANSFER_STATUS.REFUND_PENDING,
  ],
  [TRANSFER_STATUS.REFUND_PENDING]: [TRANSFER_STATUS.REFUNDED],
  [TRANSFER_STATUS.DISPUTED]: [
    TRANSFER_STATUS.REFUND_PENDING,
    TRANSFER_STATUS.REFUNDED,
    TRANSFER_STATUS.COMPLETED,
    TRANSFER_STATUS.ADMIN_CANCELLED,
  ],
};

export function canTransitionTransferStatus(from, to) {
  const fromN = normalizeTransferStatus(from);
  const toN = normalizeTransferStatus(to);
  const allowed = TRANSFER_TRANSITIONS[fromN] || [];
  return allowed.includes(toN);
}

/**
 * @param {string} from
 * @param {string} to
 * @param {'customer'|'supplier'|'admin'|'system'} actor
 */
export function canActorTransition(from, to, actor) {
  if (!canTransitionTransferStatus(from, to)) return false;
  const toN = normalizeTransferStatus(to);
  const a = String(actor || "system");

  if (a === "system") return true;
  if (a === "admin") return true;

  if (a === "customer") {
    return [
      TRANSFER_STATUS.CUSTOMER_CANCELLED,
      TRANSFER_STATUS.OPEN_FOR_CLAIM,
    ].includes(toN);
  }

  if (a === "supplier") {
    return [
      TRANSFER_STATUS.CLAIMED,
      TRANSFER_STATUS.SUPPLIER_CANCELLED,
      TRANSFER_STATUS.DRIVER_ASSIGNED,
      TRANSFER_STATUS.DRIVER_EN_ROUTE,
      TRANSFER_STATUS.PASSENGER_PICKED_UP,
      TRANSFER_STATUS.COMPLETED,
    ].includes(toN);
  }

  return false;
}

export function defaultTransferCommissionPercent() {
  const n = Number(process.env.TRANSFER_COMMISSION_PERCENT || 15);
  return Number.isFinite(n) && n >= 0 && n <= 100 ? n : 15;
}

/** Default offer window before EXPIRED_UNCLAIMED (hours). */
export function defaultOfferTtlHours() {
  const n = Number(process.env.TRANSFER_OFFER_TTL_HOURS || 24);
  return Number.isFinite(n) && n > 0 ? n : 24;
}
